# Specify the build settings
[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

# Deployment settings
[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckDisabled = false

# Services configuration
[services]

# Main service for SSH
[services.main]
type = "tcp"  # TCP proxy for SSH
port = 22     # Internal port (mapped dynamically)

[services.main.tcp]
# Allow Railway to assign an external port dynamically
external_port = "auto"

# Environment variable settings
[services.main.env]
SSH_PASSWORD = "adminpass"  # Set this securely in Railway's environment settings
