[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckDisabled = true

[services]
[services.main]
type = "tcp"  # Specify TCP proxy for SSH
port = 22     # Internal container port

[services.main.tcp]
external_port = 8080  # Map Railway's external port
